### ISSUE TITLE
Gauge is missing from metrics-registry.js

### ISSUE THREAD

**Issue by vshamgin** [rstiller/inspector-metrics#1]
The version of metrics-registry.js in npm has Gauge missing

**Comment by rstiller** [comment]
Since `Gauge` is a typescript interface (like `Counter` or `Metric`) is it not exported to javascript.
May be the default implementation `SimpleGauge` is suitable for your usecase.

I googled a bit and found:
https://stackoverflow.com/questions/3710275/does-javascript-have-the-interface-type-such-as-javas-interface

I may need to more clear in the README but this lib is intended to be used with typescript in nodejs - here you can find all the interface definitions in *.d.ts files.

I haven't put much effort in any javascript usage scenario.

**Comment by rstiller** [comment]
@vshamgin I'll close the issue for now. If your question/suggestion is not answered, feel free to repoen it again.
