### ISSUE TITLE
Make metrics setters return this

### ISSUE THREAD

**Issue by doubret** [rstiller/inspector-metrics#7]
Is it ok for you to let the metrics methods return this ?

```
    public setGroup(group: string): this {
        this.group = group;
        return this;
    }
```

This way we can chain calls like :
```
const gauge = new SimpleGauge("gauge")
    .setTag('tagkey', 'tagvalue')
    .setTag('tagkey2', 'tagvalue2');
```

If it's ok for you, i can change the code and make a pull request.

**Comment by rstiller** [comment]
Sure go ahead.
Since only void is returned for now, it should not break anything.

If you do a PullRequest the following functions in class `BaseMetric` (lib/metrics/metric.ts) should be considered to return `this`:
- setMetadata
- setGroup
- setName
- setDescription
- setTag

If cou can wait until tomorrow evening, I can do it too.

**Comment by doubret** [comment]
I agree that it should not break anything. 
I will send you the pull request this evening, it should not be long to make the change

**Comment by doubret** [comment]
Done. 
I aplied the return this pattern on `BaseMetric` class and other classes where it made sense.
